#!/bin/bash

target_dir=${1:-"."}
source_baseline=${2:-"https://github.com/bltavares/vagrant-baseline.git"}

[[ -d $target_dir ]] || mkdir -p $target_dir
(
 cd $target_dir
 if [[ -d "./.baseline" ]]; then
   echo "Baseline project already created."
 else
   git clone $source_baseline .baseline
 fi
 echo ".baseline" >> .gitignore
 cd .baseline
 git update-index --assume-unchanged puppet/config.yaml
)
