#!/bin/sh

_baseline_readlink() {
  (
  TARGET_FILE=$1

  cd `dirname $TARGET_FILE`
  TARGET_FILE=`basename $TARGET_FILE`

  while [ -L "$TARGET_FILE" ]
  do
    TARGET_FILE=`readlink $TARGET_FILE`
    cd `dirname $TARGET_FILE`
    TARGET_FILE=`basename $TARGET_FILE`
  done

  PHYS_DIR=`pwd -P`
  RESULT=$PHYS_DIR/$TARGET_FILE
  echo $RESULT
  )
}

path_to_baseline=`which baseline`
if [[ `uname` == "Darwin" ]]; then
  dirname $(dirname `_baseline_readlink "$path_to_baseline"`)
else
  dirname $(dirname `readlink -f "$path_to_baseline"`)
fi
