#!/bin/bash

stop_unless_baseline_project

(
 cd .baseline
 export host_name=`echo "$@" | tr " " "-"`
 if [[ "x$host_name" == "x" ]]; then
    unset host_name
    [[ -f .hostname ]] && \
      export host_name=`cat .hostname | tr "\n" "-" | sed -e "s/-$//"`
 else
    echo "$@" | tr " " "\n" > .hostname
 fi
 export baseline_kickstart=`echo $host_name | tr "-" " "`
 vagrant up --provision
)
